# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('altitude', models.FloatField(null=True)),
                ('co', models.FloatField(null=True)),
                ('co_aux', models.FloatField(null=True)),
                ('co_working', models.FloatField(null=True)),
                ('gas_temp', models.FloatField(null=True)),
                ('gps_fix', models.IntegerField(null=True)),
                ('heading', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('lonet_bat', models.IntegerField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('no2', models.FloatField(null=True)),
                ('no2_aux', models.FloatField(null=True)),
                ('no2_working', models.FloatField(null=True)),
                ('pm1', models.FloatField(null=True)),
                ('pm10', models.FloatField(null=True)),
                ('pm2_5', models.FloatField(null=True)),
                ('w_pm1', models.FloatField(null=True)),
                ('w_pm10', models.FloatField(null=True)),
                ('w_pm2_5', models.FloatField(null=True)),
                ('sample_flow_rate', models.FloatField(null=True)),
                ('sampling_period', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('temp', models.FloatField(null=True)),
                ('date', models.FloatField()),
                ('retries', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together=set([('id', 'timestamp')]),
        ),
    ]
