# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganicityToken',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(max_length=1024)),
                ('access_token_expires', models.IntegerField()),
                ('refresh_token_expires', models.IntegerField()),
                ('being_refreshed', models.IntegerField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='last_organicity_sync',
            field=models.DateTimeField(null=True),
        )
    ]
