# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 01:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0003_auto_20161210_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicitytoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        )
    ]
