# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0004_auto_20161210_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawReading',
            fields=[
                ('altitude', models.FloatField(null=True)),
                ('co_a', models.FloatField(null=True)),
                ('co_w', models.FloatField(null=True)),
                ('pt', models.FloatField(null=True)),
                ('gps_fix', models.IntegerField(null=True)),
                ('heading', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('lonet_bat', models.IntegerField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('no2_a', models.FloatField(null=True)),
                ('no2_w', models.FloatField(null=True)),
                ('pm1', models.FloatField(null=True)),
                ('pm10', models.FloatField(null=True)),
                ('pm2_5', models.FloatField(null=True)),
                ('w_pm1', models.FloatField(null=True)),
                ('w_pm10', models.FloatField(null=True)),
                ('w_pm2_5', models.FloatField(null=True)),
                ('sample_flow_rate', models.FloatField(null=True)),
                ('sampling_period', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('temp', models.FloatField(null=True)),
                ('date', models.FloatField()),
                ('retries', models.IntegerField()),
                ('last_organicity_sync', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rawreading',
            unique_together=set([('id', 'timestamp')]),
        ),
    ]
