# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0006_auto_20170209_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaqnGroup',
            fields=[
                ('group_name', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('website_url', models.CharField(blank=True, max_length=2048)),
                ('last_laqn_sync', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LaqnReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=2048)),
                ('species_code', models.CharField(max_length=2048)),
                ('timestamp', models.DateTimeField(null=True)),
                ('value', models.FloatField(null=True)),
                ('last_laqn_sync', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LaqnSite',
            fields=[
                ('site_code', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('local_authority_code', models.CharField(max_length=2048)),
                ('local_authority_name', models.CharField(max_length=2048)),
                ('site_name', models.CharField(max_length=2048)),
                ('site_type', models.CharField(max_length=2048)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('date_opened', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude_wgs84', models.FloatField(null=True)),
                ('longitude_wgs84', models.FloatField(null=True)),
                ('data_owner', models.CharField(blank=True, max_length=2048)),
                ('data_manager', models.CharField(blank=True, max_length=2048)),
                ('site_link', models.CharField(blank=True, max_length=2048)),
                ('last_laqn_sync', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='laqnreading',
            unique_together=set([('site_code', 'timestamp', 'species_code')]),
        ),
    ]
