# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0007_auto_20170210_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawreading',
            name='bat_v',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rawreading',
            name='location_std',
            field=models.FloatField(null=True),
        )
    ]
