# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:00
from __future__ import unicode_literals
from django.db import migrations, transaction, connection


@transaction.atomic
def add_first_last_aggregates(apps, schema_editor):
    cur = connection.cursor()
    cur.execute("""
-- Create a function that always returns the first non-NULL item
CREATE OR REPLACE FUNCTION public.first_agg ( anyelement, anyelement )
RETURNS anyelement LANGUAGE SQL IMMUTABLE STRICT AS $$
        SELECT $1;
$$;

-- And then wrap an aggregate around it
CREATE AGGREGATE public.FIRST (
        sfunc    = public.first_agg,
        basetype = anyelement,
        stype    = anyelement
);

-- Create a function that always returns the last non-NULL item
CREATE OR REPLACE FUNCTION public.last_agg ( anyelement, anyelement )
RETURNS anyelement LANGUAGE SQL IMMUTABLE STRICT AS $$
        SELECT $2;
$$;

-- And then wrap an aggregate around it
CREATE AGGREGATE public.LAST (
        sfunc    = public.last_agg,
        basetype = anyelement,
        stype    = anyelement
);
""")


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0008_auto_20170215_1500'),
    ]

    operations = [
        migrations.RunPython(add_first_last_aggregates)
    ]
