# Generated by Django 2.1.1 on 2018-09-20 21:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0011_auto_20180919_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientexperiment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_experiments', to='thingapi.Client'),
        ),
        migrations.AlterField(
            model_name='clientexperiment',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_experiments', to='thingapi.Experiment'),
        )
    ]
