# Generated by Django 2.1.1 on 2018-09-21 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import thingapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0012_auto_20180920_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetimerange',
            name='species',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetimerange',
            name='calibration_model_args',
            field=models.TextField(default=thingapi.models.no_loader_args),
        ),
        migrations.AlterField(
            model_name='devicetimerange',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicetimerange',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_time_ranges', to='thingapi.Experiment'),
        ),
        migrations.AlterField(
            model_name='devicetimerange',
            name='start_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
