# Generated by Django 2.1.1 on 2018-09-27 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0013_auto_20180921_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawReadingV4',
            fields=[
                ('ver', models.IntegerField(null=True)),
                ('rtys', models.IntegerField(null=True)),
                ('vol', models.IntegerField(null=True)),
                ('afewrk1', models.IntegerField(null=True)),
                ('afeaux1', models.IntegerField(null=True)),
                ('afewrk2', models.IntegerField(null=True)),
                ('afeaux2', models.IntegerField(null=True)),
                ('afewrk3', models.IntegerField(null=True)),
                ('afeaux3', models.IntegerField(null=True)),
                ('afept1k', models.IntegerField(null=True)),
                ('isbwrk', models.IntegerField(null=True)),
                ('isbaux', models.IntegerField(null=True)),
                ('mics1', models.IntegerField(null=True)),
                ('mics2', models.IntegerField(null=True)),
                ('time', models.CharField(max_length=256, null=True)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('alt', models.FloatField(null=True)),
                ('fix', models.IntegerField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('head', models.FloatField(null=True)),
                ('rpm', models.IntegerField(null=True)),
                ('pm11c', models.IntegerField(null=True)),
                ('pm125c', models.IntegerField(null=True)),
                ('pm110c', models.IntegerField(null=True)),
                ('pm11a', models.IntegerField(null=True)),
                ('pm125a', models.IntegerField(null=True)),
                ('pm110a', models.IntegerField(null=True)),
                ('pm1par3', models.IntegerField(null=True)),
                ('pm1par5', models.IntegerField(null=True)),
                ('pm1par10', models.IntegerField(null=True)),
                ('pm1par25', models.IntegerField(null=True)),
                ('pm1tmp', models.IntegerField(null=True)),
                ('pm1hum', models.IntegerField(null=True)),
                ('pm21c', models.IntegerField(null=True)),
                ('pm225c', models.IntegerField(null=True)),
                ('pm210c', models.IntegerField(null=True)),
                ('pm21a', models.IntegerField(null=True)),
                ('pm225a', models.IntegerField(null=True)),
                ('pm210a', models.IntegerField(null=True)),
                ('pm2par3', models.IntegerField(null=True)),
                ('pm2par5', models.IntegerField(null=True)),
                ('pm2par10', models.IntegerField(null=True)),
                ('pm2par25', models.IntegerField(null=True)),
                ('pm2tmp', models.IntegerField(null=True)),
                ('pm2hum', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rawreadingv4',
            unique_together={('id', 'timestamp')},
        ),
    ]
