# Generated by Django 2.1.1 on 2018-10-07 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0014_auto_20180927_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='METField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='METPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='METReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=16)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thingapi.METField')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thingapi.METPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='METSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('mode', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='metsite',
            unique_together={('site_id', 'mode')},
        ),
        migrations.AddField(
            model_name='metreading',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thingapi.METSite'),
        ),
        migrations.AlterUniqueTogether(
            name='metperiod',
            unique_together={('start_time', 'duration')},
        ),
        migrations.AlterUniqueTogether(
            name='metfield',
            unique_together={('name', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='metreading',
            unique_together={('period', 'field', 'site')},
        ),
    ]
