# Generated by Django 2.1.1 on 2018-10-11 10:18

import datetime
from django.db import migrations, models
import thingapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0015_auto_20181007_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('weather_loader', models.CharField(max_length=128)),
                ('weather_args', models.TextField(default=thingapi.models.no_loader_args)),
            ],
        )
    ]
