# Generated by Django 2.1.1 on 2018-10-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0015_auto_20181008_0900'),
        ('thingapi', '0017_auto_20181014_1803'),
    ]

    operations = [
    ]
