# Generated by Django 2.1.1 on 2018-10-26 19:48

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0018_merge_20181023_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawreadingv4',
            name='time',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
