# Generated by Django 2.1.1 on 2018-10-27 21:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0019_auto_20181026_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(related_name='clients', through='thingapi.ClientUser', to=settings.AUTH_USER_MODEL),
        )
    ]
