# Generated by Django 2.1.1 on 2019-01-27 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0020_auto_20181027_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecomputedLoaderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('results_as_dataframe', models.BinaryField()),
                ('device_ids_as_json', models.CharField(max_length=1024)),
                ('species_as_json', models.CharField(max_length=1024)),
                ('dummy_locations', models.BinaryField()),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('device_time_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thingapi.DeviceTimeRange')),
            ],
        ),
    ]
