# Generated by Django 2.1.1 on 2020-03-28 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thingapi', '0023_auto_20191125_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLoraReadingV4',
            fields=[
                ('id', models.IntegerField()),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('ver', models.IntegerField()),
                ('rtys', models.IntegerField()),
                ('vol', models.FloatField()),
                ('afewrk1', models.FloatField()),
                ('afeaux1', models.FloatField()),
                ('afewrk2', models.FloatField()),
                ('afeaux2', models.FloatField()),
                ('afewrk3', models.FloatField()),
                ('afeaux3', models.FloatField()),
                ('afept1k', models.FloatField()),
                ('isbwrk', models.FloatField()),
                ('isbaux', models.FloatField()),
                ('mics1', models.FloatField()),
                ('mics2', models.FloatField()),
                ('rpm', models.FloatField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('pm11c', models.FloatField()),
                ('pm125c', models.FloatField()),
                ('pm110c', models.FloatField()),
                ('pm1tmp', models.FloatField()),
                ('pm1hum', models.FloatField()),
                ('pm21c', models.FloatField()),
                ('pm225c', models.FloatField()),
                ('pm210c', models.FloatField()),
                ('pm2tmp', models.FloatField()),
                ('pm2hum', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rawlorareadingv4',
            unique_together={('id', 'timestamp')},
        ),
    ]
